// Generated by software/fhe/params.py -- DO NOT EDIT.
// Regenerate with: python3 software/fhe/params.py
//
// RNS primes q_i < 2^31 with q_i == 1 (mod 2N), the minimum 2N-th
// primitive root per prime, and Montgomery constants for R = 2^32.

/// Montgomery constants and the NTT root for one RNS prime.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub struct PrimeParams {
    /// The prime modulus, < 2^31.
    pub q: u32,
    /// Minimum primitive 2N-th root of unity mod q.
    pub root: u32,
    /// Inverse of `root` mod q.
    pub root_inv: u32,
    /// N^-1 mod q (scaling for the inverse transform).
    pub n_inv: u32,
    /// -q^-1 mod 2^32 (Montgomery n').
    pub q_inv_neg: u32,
    /// 2^64 mod q (converts into Montgomery form).
    pub r2: u32,
    /// 2^32 mod q (Montgomery form of 1).
    pub r1: u32,
}

/// One parameter point: ring degree, RNS depth and its primes.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub struct ParamSet {
    /// Short name, matches the `FHE_PARAMS=` build knob.
    pub name: &'static str,
    /// log2 of the ring degree.
    pub log_n: u32,
    /// Ring degree N.
    pub n: usize,
    /// Number of RNS limbs L.
    pub level: usize,
    /// log2 of the CKKS scale delta.
    pub scale_bits: u32,
    /// The L primes, limb 0 first.
    pub primes: &'static [PrimeParams],
}

impl ParamSet {
    /// Bytes in one RNS plaintext polynomial (`POLY_INT_32`).
    pub const fn pt_bytes(&self) -> usize {
        self.level * self.n * 4
    }
    /// Bytes in one ciphertext (`c0` limbs then `c1` limbs).
    pub const fn ct_bytes(&self) -> usize {
        2 * self.level * self.n * 4
    }
    /// `u32` words in one RNS plaintext polynomial.
    pub const fn pt_words(&self) -> usize {
        self.level * self.n
    }
    /// `u32` words in one ciphertext.
    pub const fn ct_words(&self) -> usize {
        2 * self.level * self.n
    }
}

/// P-S: N=256, L=2, 30-bit primes, log q = 60.
pub const PS_PRIMES: [PrimeParams; 2] = [
    PrimeParams {
        q: 0x3ffff401,
        root: 0x006a92e4,
        root_inv: 0x21331e0a,
        n_inv: 0x3fbff40d,
        q_inv_neg: 0x7f6ff3ff,
        r2: 0x08fe8010,
        r1: 0x00002ffc,
    },
    PrimeParams {
        q: 0x3fffdc01,
        root: 0x0041ccdd,
        root_inv: 0x2a9466b6,
        n_inv: 0x3fbfdc25,
        q_inv_neg: 0xfaefdbff,
        r2: 0x10fba40f,
        r1: 0x00008ffc,
    },
];

/// P-S parameter point.
pub const PS: ParamSet = ParamSet {
    name: "ps",
    log_n: 8,
    n: 256,
    level: 2,
    scale_bits: 20,
    primes: &PS_PRIMES,
};

/// P-L: N=8192, L=2, 30-bit primes, log q = 60.
pub const PL_PRIMES: [PrimeParams; 2] = [
    PrimeParams {
        q: 0x3fff4001,
        root: 0x0000ceb9,
        root_inv: 0x0e92bdb4,
        n_inv: 0x3ffd4007,
        q_inv_neg: 0xafff3fff,
        r2: 0x0002ffec,
        r1: 0x0002fffc,
    },
    PrimeParams {
        q: 0x3ffe8001,
        root: 0x00017d0c,
        root_inv: 0x084745b1,
        n_inv: 0x3ffc800d,
        q_inv_neg: 0xfffe7fff,
        r2: 0x00a7ff80,
        r1: 0x0005fffc,
    },
];

/// P-L parameter point.
pub const PL: ParamSet = ParamSet {
    name: "pl",
    log_n: 13,
    n: 8192,
    level: 2,
    scale_bits: 20,
    primes: &PL_PRIMES,
};

/// P-L-eq: N=8192, L=4, 27-bit primes, log q = 108.
pub const PLEQ_PRIMES: [PrimeParams; 4] = [
    PrimeParams {
        q: 0x07fa8001,
        root: 0x0000182c,
        root_inv: 0x07cfeba1,
        n_inv: 0x07fa402d,
        q_inv_neg: 0xc7fa7fff,
        r2: 0x05275999,
        r1: 0x00afffe0,
    },
    PrimeParams {
        q: 0x07f74001,
        root: 0x00007666,
        root_inv: 0x006e67f7,
        n_inv: 0x07f70047,
        q_inv_neg: 0x77f73fff,
        r2: 0x0773d1fd,
        r1: 0x0117ffe0,
    },
    PrimeParams {
        q: 0x07f6c001,
        root: 0x00001318,
        root_inv: 0x078b8ea1,
        n_inv: 0x07f6804b,
        q_inv_neg: 0x77f6bfff,
        r2: 0x031dca59,
        r1: 0x0127ffe0,
    },
    PrimeParams {
        q: 0x07f54001,
        root: 0x00003ec6,
        root_inv: 0x02d4c399,
        n_inv: 0x07f50057,
        q_inv_neg: 0x77f53fff,
        r2: 0x065b6dfe,
        r1: 0x0157ffe0,
    },
];

/// P-L-eq parameter point.
pub const PLEQ: ParamSet = ParamSet {
    name: "pleq",
    log_n: 13,
    n: 8192,
    level: 4,
    scale_bits: 18,
    primes: &PLEQ_PRIMES,
};

/// Every parameter point, in plan §2.3 order.
pub const ALL: [&ParamSet; 3] = [&PS, &PL, &PLEQ];

/// Look up a parameter point by its short name.
pub fn by_name(name: &str) -> Option<&'static ParamSet> {
    let mut i = 0;
    while i < ALL.len() {
        if str_eq(ALL[i].name, name) {
            return Some(ALL[i]);
        }
        i += 1;
    }
    None
}

fn str_eq(a: &str, b: &str) -> bool {
    a.as_bytes() == b.as_bytes()
}
