/*++

Licensed under the Apache-2.0 license.

File Name:

    sample.rs

Abstract:

    The three samplers of plan §4.4, driven by the ChaCha20 PRG.

    Their *stream order* is part of the interface: the golden vectors are
    generated by drawing `s` at keygen, then, per command, `e` once and `a`
    once per RNS limb.  Any implementation that draws in a different order
    produces different ciphertexts even with the same seed, so the order is
    fixed here and asserted by the vector tests.

--*/

use crate::arith::from_i32;
use crate::prg::ChaCha20Prg;
use crate::{Error, Result};

/// Centered-binomial parameter: `sigma = sqrt(eta/2) = sqrt(10) = 3.162`,
/// the "sigma ~ 3.2" of plan §2.1.
pub const CBD_ETA: u32 = 20;

/// Bytes of keystream consumed per centered-binomial coefficient.
pub const CBD_BYTES: usize = ((2 * CBD_ETA as usize) + 7) / 8;

/// Bytes needed to hold a packed ternary secret of `n` coefficients.
pub const fn packed_secret_bytes(n: usize) -> usize {
    n / 4
}

/// Sample a uniform ternary secret, packed 2 bits per coefficient.
///
/// One keystream byte per coefficient; `0xFF` is rejected so the remaining
/// 255 values map onto `{0, 1, 2}` without bias.  Encoding: `0 -> 0`,
/// `1 -> +1`, `2 -> -1` (plan §4.4).
pub fn sample_ternary_packed(prg: &mut ChaCha20Prg, n: usize, out: &mut [u8]) -> Result<()> {
    if out.len() != packed_secret_bytes(n) || n % 4 != 0 {
        return Err(Error::BadLength);
    }
    out.fill(0);
    let mut i = 0usize;
    while i < n {
        let b = prg.next_u8();
        if b == 0xFF {
            continue;
        }
        let code = b % 3;
        out[i / 4] |= code << (2 * (i % 4));
        i += 1;
    }
    Ok(())
}

/// Read coefficient `i` of a packed ternary secret as `-1`, `0` or `+1`.
#[inline(always)]
pub fn unpack_ternary(packed: &[u8], i: usize) -> i32 {
    match (packed[i / 4] >> (2 * (i % 4))) & 0b11 {
        0 => 0,
        1 => 1,
        _ => -1,
    }
}

/// Sample a centered-binomial error polynomial into `out`.
///
/// `CBD_BYTES` keystream bytes per coefficient, read little-endian:
/// `e = popcount(low eta bits) - popcount(next eta bits)`, so
/// `e` lies in `[-eta, eta]` and fits `i8` for every eta we use.
pub fn sample_cbd(prg: &mut ChaCha20Prg, out: &mut [i8]) {
    let mask: u64 = (1u64 << CBD_ETA) - 1;
    for e in out.iter_mut() {
        let mut raw = [0u8; 8];
        prg.fill(&mut raw[..CBD_BYTES]);
        let w = u64::from_le_bytes(raw);
        let a = (w & mask).count_ones() as i32;
        let b = ((w >> CBD_ETA) & mask).count_ones() as i32;
        *e = (a - b) as i8;
    }
}

/// Sample uniformly modulo `q` into `out`.
///
/// One keystream `u32` per draw, masked to `bit_length(q)` bits and rejected
/// if it is not below `q`.  Our primes sit just under a power of two, so the
/// rejection rate is well under 0.1 %.
pub fn sample_uniform(prg: &mut ChaCha20Prg, q: u32, out: &mut [u32]) {
    let mask = if q.leading_zeros() == 0 {
        u32::MAX
    } else {
        (1u32 << (32 - q.leading_zeros())) - 1
    };
    let mut i = 0usize;
    while i < out.len() {
        let v = prg.next_u32() & mask;
        if v < q {
            out[i] = v;
            i += 1;
        }
    }
}

/// Reduce a sampled error polynomial into one RNS limb.
pub fn cbd_to_limb(e: &[i8], q: u32, out: &mut [u32]) -> Result<()> {
    if e.len() != out.len() {
        return Err(Error::BadLength);
    }
    for (o, v) in out.iter_mut().zip(e.iter()) {
        *o = from_i32(*v as i32, q);
    }
    Ok(())
}

/// Expand a packed ternary secret into one RNS limb, in coefficient domain.
pub fn secret_to_limb(packed: &[u8], q: u32, out: &mut [u32]) -> Result<()> {
    if packed.len() != packed_secret_bytes(out.len()) {
        return Err(Error::BadLength);
    }
    for (i, o) in out.iter_mut().enumerate() {
        *o = from_i32(unpack_ternary(packed, i), q);
    }
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn ternary_pack_round_trip() {
        let mut prg = ChaCha20Prg::new(&[7u8; 32]);
        let n = 256;
        let mut packed = vec![0u8; packed_secret_bytes(n)];
        sample_ternary_packed(&mut prg, n, &mut packed).unwrap();
        let mut counts = [0usize; 3];
        for i in 0..n {
            let v = unpack_ternary(&packed, i);
            assert!((-1..=1).contains(&v));
            counts[(v + 1) as usize] += 1;
        }
        // uniform ternary: every value must actually appear
        assert!(counts.iter().all(|c| *c > 0), "{counts:?}");
    }

    #[test]
    fn cbd_is_centered_and_bounded() {
        let mut prg = ChaCha20Prg::new(&[9u8; 32]);
        let mut e = vec![0i8; 4096];
        sample_cbd(&mut prg, &mut e);
        let eta = CBD_ETA as i8;
        assert!(e.iter().all(|v| *v >= -eta && *v <= eta));
        let sum: i32 = e.iter().map(|v| *v as i32).sum();
        assert!(sum.abs() < 1000, "mean too far from zero: {sum}");
        let var: i64 = e.iter().map(|v| (*v as i64) * (*v as i64)).sum::<i64>() / 4096;
        assert!(
            (8..=13).contains(&var),
            "variance {var} not near eta/2 = 10"
        );
    }

    #[test]
    fn uniform_stays_below_q() {
        let q = crate::params::PS.primes[0].q;
        let mut prg = ChaCha20Prg::new(&[1u8; 32]);
        let mut a = vec![0u32; 1024];
        sample_uniform(&mut prg, q, &mut a);
        assert!(a.iter().all(|v| *v < q));
        assert!(a.iter().any(|v| *v > q / 2));
    }
}
